config/routes.rb
FleetMgt::Application.routes.draw do
  resources :managers

  resources :statuses

  resources :railcar_types

  resources :railcars

  resources :demands

  resources :orders

  resources :contacts

  resources :clients

  resources :users

  resources :carriers

  resources :states

  resources :stations

  resources :facilities

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :Active, :Code, :Name
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :Active, :LAM_ID, :Name

  

  scope :active, where(active: true)
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :Active, :Client_ID, :First_Name, :Last_Name, :User_ID, :email

  has_many :orders
  has_one :manager

  scope :active, where(active: true)
end

app/models/demand.rb
class Demand < ActiveRecord::Base
  attr_accessible :Order_ID, :Railcar_ID
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  attr_accessible :Active, :Address_1, :Address_2, :Carrier_ID, :City, :Name, :Postal_Code, :Routing_Notes, :State_ID, :Station_ID
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  attr_accessible :Active, :First_Name, :Last_Name, :email, :full_name

  has_many :orders

  def full_name
  	"#{First_Name} #{Last_Name}"
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :Contact_ID, :Facility_ID, :Manager_ID, :Railcar_Demand, :Railcar_Type_ID, :Status_ID

  belongs_to :manager 
  has_one :status 

end

app/models/railcar.rb
class Railcar < ActiveRecord::Base
  attr_accessible :Active, :Capacity, :GWR, :Initial, :Inside_Length, :Number, :Railcar_Type_ID
end

app/models/railcar_type.rb
class RailcarType < ActiveRecord::Base
  attr_accessible :Active, :Description, :Name

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :Code, :Name
end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :Active, :City, :State_ID
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :Code, :Description

  has_many :orders

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @managers }
    end
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
    @manager = Manager.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/new
  # GET /managers/new.json
  def new
    @manager = Manager.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/1/edit
  def edit
    @manager = Manager.find(params[:id])
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(params[:manager])

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render json: @manager, status: :created, location: @manager }
      else
        format.html { render action: "new" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /managers/1
  # PUT /managers/1.json
  def update
    @manager = Manager.find(params[:id])

    respond_to do |format|
      if @manager.update_attributes(params[:manager])
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager = Manager.find(params[:id])
    @manager.destroy

    respond_to do |format|
      format.html { redirect_to managers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/railcars_helper.rb
module RailcarsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/managers/_form.html.erb
<%= form_for(@manager) do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% @manager.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :First_Name %><br />
    <%= f.text_field :First_Name %>
  </div>
  <div class="field">
    <%= f.label :Last_Name %><br />
    <%= f.text_field :Last_Name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Active %><br />
    <%= f.check_box :Active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<h1>Listing managers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @managers.each do |manager| %>
  <tr>
    <td><%= manager.First_Name %></td>
    <td><%= manager.Last_Name %></td>
    <td><%= manager.email %></td>
    <td><%= manager.Active %></td>
    <td><%= link_to 'Show', manager %></td>
    <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
    <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Manager', new_manager_path %>

app/views/managers/new.html.erb
<h1>New manager</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @manager.First_Name %>
</p>

<p>
  <b>Last name:</b>
  <%= @manager.Last_Name %>
</p>

<p>
  <b>Email:</b>
  <%= @manager.email %>
</p>

<p>
  <b>Active:</b>
  <%= @manager.Active %>
</p>


<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>