config/routes.rb
FleetMgt::Application.routes.draw do
  resources :managers

  resources :statuses

  resources :railcar_types

  resources :railcars

  resources :demands

  resources :orders

  resources :contacts

  resources :clients

  resources :users

  resources :carriers

  resources :states

  resources :stations

  resources :facilities

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :Active, :Code, :Name
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :Active, :LAM_ID, :Name

  

  scope :active, where(active: true)
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :Active, :Client_ID, :First_Name, :Last_Name, :User_ID, :email

  has_many :orders
  has_one :manager

  scope :active, where(active: true)
end

app/models/demand.rb
class Demand < ActiveRecord::Base
  attr_accessible :Order_ID, :Railcar_ID
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  attr_accessible :Active, :Address_1, :Address_2, :Carrier_ID, :City, :Name, :Postal_Code, :Routing_Notes, :State_ID, :Station_ID
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  attr_accessible :Active, :First_Name, :Last_Name, :email, :full_name

  has_many :orders

  def full_name
  	"#{First_Name} #{Last_Name}"
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :Contact_ID, :Facility_ID, :Manager_ID, :Railcar_Demand, :Railcar_Type_ID, :Status_ID

  belongs_to :manager 
  has_one :status 

end

app/models/railcar.rb
class Railcar < ActiveRecord::Base
  attr_accessible :Active, :Capacity, :GWR, :Initial, :Inside_Length, :Number, :Railcar_Type_ID
end

app/models/railcar_type.rb
class RailcarType < ActiveRecord::Base
  attr_accessible :Active, :Description, :Name

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :Code, :Name
end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :Active, :City, :State_ID
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :Code, :Description

  has_many :orders

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  # GET /demands
  # GET /demands.json
  def index
    @demands = Demand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @demands }
    end
  end

  # GET /demands/1
  # GET /demands/1.json
  def show
    @demand = Demand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @demand }
    end
  end

  # GET /demands/new
  # GET /demands/new.json
  def new
    @demand = Demand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @demand }
    end
  end

  # GET /demands/1/edit
  def edit
    @demand = Demand.find(params[:id])
  end

  # POST /demands
  # POST /demands.json
  def create
    @demand = Demand.new(params[:demand])

    respond_to do |format|
      if @demand.save
        format.html { redirect_to @demand, notice: 'Demand was successfully created.' }
        format.json { render json: @demand, status: :created, location: @demand }
      else
        format.html { render action: "new" }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /demands/1
  # PUT /demands/1.json
  def update
    @demand = Demand.find(params[:id])

    respond_to do |format|
      if @demand.update_attributes(params[:demand])
        format.html { redirect_to @demand, notice: 'Demand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demands/1
  # DELETE /demands/1.json
  def destroy
    @demand = Demand.find(params[:id])
    @demand.destroy

    respond_to do |format|
      format.html { redirect_to demands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/railcars_helper.rb
module RailcarsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/demands/_form.html.erb
<%= form_for(@demand) do |f| %>
  <% if @demand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demand.errors.count, "error") %> prohibited this demand from being saved:</h2>

      <ul>
      <% @demand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Order_ID %><br />
    <%= f.number_field :Order_ID %>
  </div>
  <div class="field">
    <%= f.label :Railcar_ID %><br />
    <%= f.number_field :Railcar_ID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demands/edit.html.erb
<h1>Editing demand</h1>

<%= render 'form' %>

<%= link_to 'Show', @demand %> |
<%= link_to 'Back', demands_path %>

app/views/demands/index.html.erb
<h1>Listing demands</h1>

<table>
  <tr>
    <th>Order id</th>
    <th>Railcar id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @demands.each do |demand| %>
  <tr>
    <td><%= demand.Order_ID %></td>
    <td><%= demand.Railcar_ID %></td>
    <td><%= link_to 'Show', demand %></td>
    <td><%= link_to 'Edit', edit_demand_path(demand) %></td>
    <td><%= link_to 'Destroy', demand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Demand', new_demand_path %>

app/views/demands/new.html.erb
<h1>New demand</h1>

<%= render 'form' %>

<%= link_to 'Back', demands_path %>

app/views/demands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order id:</b>
  <%= @demand.Order_ID %>
</p>

<p>
  <b>Railcar id:</b>
  <%= @demand.Railcar_ID %>
</p>


<%= link_to 'Edit', edit_demand_path(@demand) %> |
<%= link_to 'Back', demands_path %>