config/routes.rb
FleetMgt::Application.routes.draw do
  resources :managers

  resources :statuses

  resources :railcar_types

  resources :railcars

  resources :demands

  resources :orders

  resources :contacts

  resources :clients

  resources :users

  resources :carriers

  resources :states

  resources :stations

  resources :facilities

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :Active, :Code, :Name
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :Active, :LAM_ID, :Name

  

  scope :active, where(active: true)
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :Active, :Client_ID, :First_Name, :Last_Name, :User_ID, :email

  has_many :orders
  has_one :manager

  scope :active, where(active: true)
end

app/models/demand.rb
class Demand < ActiveRecord::Base
  attr_accessible :Order_ID, :Railcar_ID
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  attr_accessible :Active, :Address_1, :Address_2, :Carrier_ID, :City, :Name, :Postal_Code, :Routing_Notes, :State_ID, :Station_ID
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  attr_accessible :Active, :First_Name, :Last_Name, :email, :full_name

  has_many :orders

  def full_name
  	"#{First_Name} #{Last_Name}"
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :Contact_ID, :Facility_ID, :Manager_ID, :Railcar_Demand, :Railcar_Type_ID, :Status_ID

  belongs_to :manager 
  has_one :status 

end

app/models/railcar.rb
class Railcar < ActiveRecord::Base
  attr_accessible :Active, :Capacity, :GWR, :Initial, :Inside_Length, :Number, :Railcar_Type_ID
end

app/models/railcar_type.rb
class RailcarType < ActiveRecord::Base
  attr_accessible :Active, :Description, :Name

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :Code, :Name
end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :Active, :City, :State_ID
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :Code, :Description

  has_many :orders

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/railcars_controller.rb
class RailcarsController < ApplicationController
  # GET /railcars
  # GET /railcars.json
  def index
    @railcars = Railcar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @railcars }
    end
  end

  # GET /railcars/1
  # GET /railcars/1.json
  def show
    @railcar = Railcar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @railcar }
    end
  end

  # GET /railcars/new
  # GET /railcars/new.json
  def new
    @railcar = Railcar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @railcar }
    end
  end

  # GET /railcars/1/edit
  def edit
    @railcar = Railcar.find(params[:id])
  end

  # POST /railcars
  # POST /railcars.json
  def create
    @railcar = Railcar.new(params[:railcar])

    respond_to do |format|
      if @railcar.save
        format.html { redirect_to @railcar, notice: 'Railcar was successfully created.' }
        format.json { render json: @railcar, status: :created, location: @railcar }
      else
        format.html { render action: "new" }
        format.json { render json: @railcar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /railcars/1
  # PUT /railcars/1.json
  def update
    @railcar = Railcar.find(params[:id])

    respond_to do |format|
      if @railcar.update_attributes(params[:railcar])
        format.html { redirect_to @railcar, notice: 'Railcar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @railcar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railcars/1
  # DELETE /railcars/1.json
  def destroy
    @railcar = Railcar.find(params[:id])
    @railcar.destroy

    respond_to do |format|
      format.html { redirect_to railcars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/railcars_helper.rb
module RailcarsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/railcars/_form.html.erb
<%= form_for(@railcar) do |f| %>
  <% if @railcar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@railcar.errors.count, "error") %> prohibited this railcar from being saved:</h2>

      <ul>
      <% @railcar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Initial %><br />
    <%= f.text_field :Initial %>
  </div>
  <div class="field">
    <%= f.label :Number %><br />
    <%= f.text_field :Number %>
  </div>
  <div class="field">
    <%= f.label :Railcar_Type_ID %><br />
    <%= f.number_field :Railcar_Type_ID %>
  </div>
  <div class="field">
    <%= f.label :Inside_Length %><br />
    <%= f.number_field :Inside_Length %>
  </div>
  <div class="field">
    <%= f.label :Capacity %><br />
    <%= f.number_field :Capacity %>
  </div>
  <div class="field">
    <%= f.label :GWR %><br />
    <%= f.number_field :GWR %>
  </div>
  <div class="field">
    <%= f.label :Active %><br />
    <%= f.check_box :Active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railcars/edit.html.erb
<h1>Editing railcar</h1>

<%= render 'form' %>

<%= link_to 'Show', @railcar %> |
<%= link_to 'Back', railcars_path %>

app/views/railcars/index.html.erb
<h1>Listing railcars</h1>

<table>
  <tr>
    <th>Initial</th>
    <th>Number</th>
    <th>Railcar type id</th>
    <th>Inside length</th>
    <th>Capacity</th>
    <th>Gwr</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @railcars.each do |railcar| %>
  <tr>
    <td><%= railcar.Initial %></td>
    <td><%= railcar.Number %></td>
    <td><%= railcar.Railcar_Type_ID %></td>
    <td><%= railcar.Inside_Length %></td>
    <td><%= railcar.Capacity %></td>
    <td><%= railcar.GWR %></td>
    <td><%= railcar.Active %></td>
    <td><%= link_to 'Show', railcar %></td>
    <td><%= link_to 'Edit', edit_railcar_path(railcar) %></td>
    <td><%= link_to 'Destroy', railcar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Railcar', new_railcar_path %>

app/views/railcars/new.html.erb
<h1>New railcar</h1>

<%= render 'form' %>

<%= link_to 'Back', railcars_path %>

app/views/railcars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Initial:</b>
  <%= @railcar.Initial %>
</p>

<p>
  <b>Number:</b>
  <%= @railcar.Number %>
</p>

<p>
  <b>Railcar type id:</b>
  <%= @railcar.Railcar_Type_ID %>
</p>

<p>
  <b>Inside length:</b>
  <%= @railcar.Inside_Length %>
</p>

<p>
  <b>Capacity:</b>
  <%= @railcar.Capacity %>
</p>

<p>
  <b>Gwr:</b>
  <%= @railcar.GWR %>
</p>

<p>
  <b>Active:</b>
  <%= @railcar.Active %>
</p>


<%= link_to 'Edit', edit_railcar_path(@railcar) %> |
<%= link_to 'Back', railcars_path %>