config/routes.rb
FleetMgt::Application.routes.draw do
  resources :managers

  resources :statuses

  resources :railcar_types

  resources :railcars

  resources :demands

  resources :orders

  resources :contacts

  resources :clients

  resources :users

  resources :carriers

  resources :states

  resources :stations

  resources :facilities

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :Active, :Code, :Name
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :Active, :LAM_ID, :Name

  

  scope :active, where(active: true)
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :Active, :Client_ID, :First_Name, :Last_Name, :User_ID, :email

  has_many :orders
  has_one :manager

  scope :active, where(active: true)
end

app/models/demand.rb
class Demand < ActiveRecord::Base
  attr_accessible :Order_ID, :Railcar_ID
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  attr_accessible :Active, :Address_1, :Address_2, :Carrier_ID, :City, :Name, :Postal_Code, :Routing_Notes, :State_ID, :Station_ID
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  attr_accessible :Active, :First_Name, :Last_Name, :email, :full_name

  has_many :orders

  def full_name
  	"#{First_Name} #{Last_Name}"
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :Contact_ID, :Facility_ID, :Manager_ID, :Railcar_Demand, :Railcar_Type_ID, :Status_ID

  belongs_to :manager 
  has_one :status 

end

app/models/railcar.rb
class Railcar < ActiveRecord::Base
  attr_accessible :Active, :Capacity, :GWR, :Initial, :Inside_Length, :Number, :Railcar_Type_ID
end

app/models/railcar_type.rb
class RailcarType < ActiveRecord::Base
  attr_accessible :Active, :Description, :Name

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :Code, :Name
end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :Active, :City, :State_ID
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :Code, :Description

  has_many :orders

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/railcar_types_controller.rb
class RailcarTypesController < ApplicationController
  # GET /railcar_types
  # GET /railcar_types.json
  def index
    @railcar_types = RailcarType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @railcar_types }
    end
  end

  # GET /railcar_types/1
  # GET /railcar_types/1.json
  def show
    @railcar_type = RailcarType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @railcar_type }
    end
  end

  # GET /railcar_types/new
  # GET /railcar_types/new.json
  def new
    @railcar_type = RailcarType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @railcar_type }
    end
  end

  # GET /railcar_types/1/edit
  def edit
    @railcar_type = RailcarType.find(params[:id])
  end

  # POST /railcar_types
  # POST /railcar_types.json
  def create
    @railcar_type = RailcarType.new(params[:railcar_type])

    respond_to do |format|
      if @railcar_type.save
        format.html { redirect_to @railcar_type, notice: 'Railcar type was successfully created.' }
        format.json { render json: @railcar_type, status: :created, location: @railcar_type }
      else
        format.html { render action: "new" }
        format.json { render json: @railcar_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /railcar_types/1
  # PUT /railcar_types/1.json
  def update
    @railcar_type = RailcarType.find(params[:id])

    respond_to do |format|
      if @railcar_type.update_attributes(params[:railcar_type])
        format.html { redirect_to @railcar_type, notice: 'Railcar type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @railcar_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railcar_types/1
  # DELETE /railcar_types/1.json
  def destroy
    @railcar_type = RailcarType.find(params[:id])
    @railcar_type.destroy

    respond_to do |format|
      format.html { redirect_to railcar_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/railcar_types_helper.rb
module RailcarTypesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/railcar_types/_form.html.erb
<%= form_for(@railcar_type) do |f| %>
  <% if @railcar_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@railcar_type.errors.count, "error") %> prohibited this railcar_type from being saved:</h2>

      <ul>
      <% @railcar_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br />
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :Active %><br />
    <%= f.check_box :Active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railcar_types/edit.html.erb
<h1>Editing railcar_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @railcar_type %> |
<%= link_to 'Back', railcar_types_path %>

app/views/railcar_types/index.html.erb
<h1>Listing railcar_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @railcar_types.each do |railcar_type| %>
  <tr>
    <td><%= railcar_type.Name %></td>
    <td><%= railcar_type.Description %></td>
    <td><%= railcar_type.Active %></td>
    <td><%= link_to 'Show', railcar_type %></td>
    <td><%= link_to 'Edit', edit_railcar_type_path(railcar_type) %></td>
    <td><%= link_to 'Destroy', railcar_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Railcar type', new_railcar_type_path %>

app/views/railcar_types/new.html.erb
<h1>New railcar_type</h1>

<%= render 'form' %>

<%= link_to 'Back', railcar_types_path %>

app/views/railcar_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @railcar_type.Name %>
</p>

<p>
  <b>Description:</b>
  <%= @railcar_type.Description %>
</p>

<p>
  <b>Active:</b>
  <%= @railcar_type.Active %>
</p>


<%= link_to 'Edit', edit_railcar_type_path(@railcar_type) %> |
<%= link_to 'Back', railcar_types_path %>